package com.hackathon03.codeguru.exception;

public class CustomException {

    public void callObjectHavingSyntaxError() {
    Integer a =23;
    String x="Test"
    System.out.println("Inside class SyntaxError");

    }


}
